LBO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('cabinet/', include("cabinet.urls")),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabinet/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cabinet'

urlpatterns = [
	path('<int:user_id>/', views.cabinet, name='cabinet'),
	path('registration/', views.reg, name='reg'),
	path('login/', views.log, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('add/<int:friend_id>/', views.add_friend, name='add_friend')
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
	path('', views.home, name='home'),
	path("popular/", views.popular, name="popular"),
	path("book_create/", views.book_create, name="book_create"),
	path("tag/<str:slug>/", views.get_tag, name="get_tag"),
	path("tags/", views.tag_list, name="tag_list"),
	path("genre/<str:slug>/", views.get_genre, name="get_genre"),
	path("genre/", views.genre_list, name="genre_list"),
	path("book/<int:book_id>/", views.book, name="book"),
	path("book/<int:book_id>/<int:number>/", views.chapter, name="chapter"),
	path('add/<int:book_id>/', views.addbook, name='addbook'),
]

home/models.py
from django.db import models
from cabinet.models import User
import datetime
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404


class Series(models.Model):
	title = models.CharField(max_length=40)


class Book(models.Model):
	title = models.CharField(max_length=30, blank=True)
	image = models.ImageField(upload_to="images/", default="images/black.jpg")
	author_name = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
	description = models.CharField(max_length=1000)
	price = models.IntegerField()
	views = models.IntegerField(default=0)
	pub_date = models.DateTimeField('Дата публикауции', default=timezone.now)
	status = models.CharField(max_length=30, default="В процессе")
	tags = models.ManyToManyField('Tag', blank=True, related_name='books')
	genres = models.ManyToManyField('Genre', blank=True, related_name='books')
	is_stuff = models.BooleanField(default=True)
	series = models.ForeignKey(Series, on_delete = models.CASCADE, null=True, blank=True)

	def __str__(self):
		return self.title

	def in_this_week(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

	def in_this_month(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 30))

	def in_this_year(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 365))

	class Meta:
		verbose_name = 'Книга'
		verbose_name_plural = 'Книги'


class Tag(models.Model):    
	name = models.CharField(verbose_name='Название', max_length=60)     
	slug = models.SlugField(verbose_name='URL')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Тег'
		verbose_name_plural = 'Теги'


class Genre(models.Model):
	name = models.CharField(max_length=20)
	slug = models.SlugField(verbose_name='URL')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Жанр'
		verbose_name_plural = 'Жанры'

class Chapter(models.Model):
	book = models.ForeignKey(Book, on_delete = models.CASCADE)
	num = models.IntegerField()
	title = models.CharField(max_length=30, default=" ", blank=True)
	txt = models.TextField()
	pub_date = models.DateTimeField('Дата публикауции', default=timezone.now)

	class Meta:
		verbose_name = 'Глава'
		verbose_name_plural = 'Главы'

	def __str__(self):
		try:
			s = f"{self.book}: глава {self.num}"
		except:
			s = "Ошибка"
		return s


class Comment(models.Model):
	chapter = models.ForeignKey(Chapter, on_delete = models.CASCADE)
	author_name = models.ForeignKey(User, on_delete = models.CASCADE, null=True)
	comment_text = models.CharField(max_length = 50000)
	pub_date = models.DateTimeField(default = timezone.now)

	def __str__(self):
		return self.author_name

	class Meta:
		verbose_name = 'Комментарий'
		verbose_name_plural = 'Комментарии'


class Person(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE, related_name="person")
	read = models.ManyToManyField("Book", blank=True, related_name="users")
	friends = models.ManyToManyField("cabinet.User", blank=True, related_name='users')

	def __str__(self):
		return self.user.username

	class Meta:
		verbose_name = 'Людь'
		verbose_name_plural = 'Люди'

home/forms.py
from .models import Book, Chapter, Comment
from django import forms


class BookForm(forms.ModelForm):
	class Meta:
		model = Book
		fields = ['title', 'image', "description", "price", "tags", "genres"]


class ChapterForm(forms.ModelForm):
	class Meta:
		model = Chapter
		fields = ['title', 'txt']


class CommentForm(forms.Form):
	comment_text = forms.CharField(widget=forms.Textarea)

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Book, Comment, Tag, Genre, Chapter, Person
from .forms import BookForm, ChapterForm
from django.utils import timezone
import datetime


def home(request):
	return render(request, "home/home_page.html", {'user': request.user})

def addbook(request, book_id):
	book = get_object_or_404(Book, id=book_id)
	user = get_object_or_404(Person, user_id=request.user.id) #Защита от незареганных 
	user.read.add(book)
	return redirect(f"/book/{book_id}")

def popular(request):
	now = datetime.datetime.now()
	year = [timezone.now() - timezone.timedelta(365), timezone.now()]
	month = [timezone.now() - timezone.timedelta(30), timezone.now()]
	week = [timezone.now() - timezone.timedelta(7), timezone.now()]
	books_y = Book.objects.filter(pub_date__range=year).order_by("-views")
	books_m = Book.objects.filter(pub_date__range=month).order_by("-views")
	books_w = Book.objects.filter(pub_date__range=week).order_by("-views")
	return render(request, "home/section.html", {'user': request.user, "title": "Популярные", "books_y": books_y, "books_m": books_m, "books_w": books_w})

def book_create(request):
	if not request.user.is_authenticated:
		return redirect("/")
	if request.method == "POST":
		form = BookForm(request.POST)
		if form.is_valid():
			book = Book()
			data = form.cleaned_data
			book.title = data["title"] 
			book.image = data["image"] 
			book.description = data["description"] 
			book.price = data["price"] 
			book.tags = data["tags"] 
			book.genres = data["genres"] 
			book.author_name_id = request.user.id
			book.save()
			return redirect('/')
	return render(request, "home/book_create.html", {'user': request.user, "form": BookForm()})

def get_tag(request, slug):
	tag = get_object_or_404(Tag, slug=slug)
	books = tag.books.all
	return render(request, "home/for_column_view.html", {'user': request.user, "title": tag, "books": books})

def get_genre(request, slug):
	genre = get_object_or_404(Genre, slug=slug)
	books = genre.books.all
	return render(request, "home/for_column_view.html", {'user': request.user, "title": genre, "books": books})

def tag_list(request):
	tags = Tag.objects.all
	return render(request, "home/tag_list.html", {'user': request.user, "title": "Теги", "tags": tags})

def genre_list(request):
	genres = Genre.objects.all
	return render(request, "home/genre_list.html", {'user': request.user, "title": "Жанры", "genres": genres})

def rec_book(request):
	books = Book.objects.order_by('-pub_date')
	return render(request, "home/section.html", {'user': request.user, "title": "Недавние", "books": books})

def book(request, book_id):
	book = get_object_or_404(Book, id=book_id)
	book.views += 1
	book.save()
	chapters = Chapter.objects.filter(book_id=book_id).order_by("-num")
	chapters_ = chapters[::-1]
	return render(request, "home/book.html", {'user': request.user, "book": book, "chapters": chapters, "chapters_": chapters_})

def chapter(request, book_id, number):
	chapters = Chapter.objects.filter(book_id=book_id)
	chapter = chapters.get(num=number)
	book = get_object_or_404(Book, id=book_id)
	book.views += 1
	book.save()
	next_ = False
	back_ = False
	try:
		a = chapters.get(num=(number + 1))
		next_ = a
	except:
		pass

	try:
		a = chapters.get(num=(number - 1))
		back_ = a
	except:
		pass
	print(back_, next_)
	return render(request, "home/only_text.html", {'user': request.user, "chapter": chapter, "next_": next_, "back_": back_})

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>LBO</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/media_queries.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/media/images/icon.png" type="image">
</head>
<body>

{% include "home/header.html" %}
<div class="main_column element">

{% block main_content %}{% endblock %}

</div>


<div class="second_column">
	{% block second_column %}
	<div class="discount element">
		<h1>Скидка на:</h1>
		<img src="/media/images/book3.jpg" alt="" class="img_slide">
		<div class="img_title">Cупер хрень</div>
		<div class="author_name">Молодой казак</div>
	</div>
	{% endblock %}
</div>

<script type="text/javascript" src="{% static 'js/js.js' %}"></script>
<script type="text/javascript" src="{% static 'js/needed.js' %}"></script>
</body>
</html>

home/templates/home/book.html
{% extends 'home/base.html' %}

{% block main_content %}{% spaceless %}


<div class="book">
	<div class="slide">
		<img src="{{book.image.url}}" alt="" class="img_in_book">
		<a href="{% url 'home:chapter' book.id '1' %}" class="read element book_button" style="display: block;">Читать</a>
		<div class="price element book_button">{{book.price}}p.</div>
	</div>
	<div class="information">
		<a href="#" class="book_title">{{book.title}}</a><span class="status">В процессе</span>
		<a href="#" class="author_name">{{book.author_name}}</a>
		<span>Серия: </span><a href="#" class="series" style="">Интересные книги</a>
		<div class="book_genre">Жанры: {% for i in book.genres.all %}<a class="object_link" href="{% url 'home:get_genre' i.slug %}">{{i}}</a>{% endfor %}
		</div>
		<div class="book_tags">Теги: {% for i in book.tags.all %}<a class="object_link" href="{% url 'home:get_tag' i.slug %}">{{i}}</a>{% endfor %}</div>
		<div class="description">Описание: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae, unde, recusandae. Officia delectus modi incidunt corporis iure aspernatur, culpa nihil? Quibusdam nam enim quaerat. Amet omnis nesciunt aspernatur dolorum minus vel, illo. Earum voluptate, deleniti hic dolor in repellendus facilis beatae praesentium aut voluptatem similique laboriosam quae vitae laborum aspernatur eius eos vel ex corrupti cupiditate nesciunt molestias. Repudiandae ab veritatis, omnis similique nulla eligendi atque explicabo laboriosam, illo dicta libero deleniti totam tempora quam temporibus laudantium ducimus eum sapiente quidem reiciendis odio adipisci! Tempora excepturi quae fuga totam cumque, sequi aut itaque sapiente, illo ex unde error dolores consequatur?</div>
	</div>
</div>

	<div class="all_chapters">
		<header class="chapter_header">
			<h7 id="headings" onclick="chapter_header(0)">ОГЛАВЛЕНИЯ</h7>
			<h7 id="updates" onclick="chapter_header(1)">ОБНОВЛЕНИЯ</h7>
		</header>
		<div class="triangle"></div>
		<div class="chapters_wraper">
			{% for chapter in chapters %}
			<div class="chapter">
				<span class="back_inf">Была добавлена глава: </span><a class="chapter_link" href="{% url 'home:chapter' book.id chapter.num %}">Глава {{chapter.num}}: {{chapter.title}}</a>
				<div style="font-size: 14px;">{{chapter.pub_date}}</div>
			</div>
			{% endfor %}
		</div>
		<div class="chapters_wraper" style="display: none;">
			{% for chapter in chapters_ %}
			<div class="chapter" style="display: flex;">
				<a class="chapter_link" href="{% url 'home:chapter' book.id chapter.num %}">Глава {{chapter.num}}: {{chapter.title}}</a>
				<div class="back_inf" style="position: absolute; right: 30px;">{{chapter.pub_date}}</div>
			</div>
			{% endfor %}
		</div>
	</div>

{% endspaceless %}{% endblock %}

home/templates/home/book_create.html
{% extends "home/base.html" %}

{% block main_content %}{% spaceless %}
<form method="post" id="book_creation_form">
{% csrf_token %}
<ul class="book_create">
	<li class="flex_column">
		<label for="id_title">Название: </label>
		<input type="text" name="title" maxlength="30" required id="id_title">
	</li>
	<li class="flex_column">
		<label for="id_image">Изображение: </label>
		<input type="file" name="image" accept="image/*" id="id_image">
	</li>
	<li class="flex_column">
		<label for="id_price">Цена: </label>
		<input type="number" name="price" required id="id_price">
	</li>
	<li class="flex_column">
		<label for="id_tags">Теги: </label>
		<select name="tags" id="id_tags" multiple></select>
	</li>
	<li class="flex_column">
		<label for="id_genre">Жанр: </label>
		<select name="genre" id="id_genre" multiple></select>
	</li>
	<li class="flex_column">
		<label for="id_description">Описание: </label>
		<textarea name="description" maxlength="1000" required form="book_creation_form" id="id_description"></textarea>
	</li>
</ul>
</form>
{% endspaceless %}{% endblock %}

home/templates/home/book_from_list.html
<div class="book_wraper">
	<div class="m slide" style="margin-right: 10px; width: auto;">
		<a href="{% url 'home:book' book.id %}">
			<img src="{{book.image.url}}" alt="" class="img_slide">
		</a>
	</div>
	<div class="information">
		<a href="{% url 'home:book' book.id %}" class="book_title">{{book.title}}</a><span class="status">{{book.status}}</span>
		<a href="#" class="author_name">{{book.author_name}}</a>
		<div class="book_genre">Жанры: {% for i in book.genres.all %}<a class="object_link" href="{% url 'home:get_genre' i.slug %}">{{i}}</a>{% endfor %}
		</div>
		<div class="book_tags">Теги: {% for i in book.tags.all %}<a class="object_link" href="{% url 'home:get_tag' i.slug %}">{{i}}</a>{% endfor %}</div>
		<span>Серия: </span><a href="#" class="series" style="">Интересные книги</a>
	</div>
</div>

home/templates/home/footer.html
<footer class="footer">
	
</footer>

home/templates/home/for_column_view.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/media_queries.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/media/images/icon.png" type="image">
</head>
<body>

{% include "home/header.html" %}


<div class="element section_title">
	<h1>{{title}}</h1>
	<!--
	<select class="select_date">
		<option value="Год">Год</option>
		<option value="Месяц">Месяц</option>
		<option value="День">День</option>
		<option value="Час">Час</option>
	</select>
	-->
</div>

<div class="main_column element">
{% for book in books %}
{% include "home/book_from_list.html" %}
{% endfor %}
</div>


<div class="second_column will_none">
	<div class="discount element">
		<h1>Скидка на:</h1>
		<img src="/media/images/book3.jpg" alt="" class="img_slide">
		<div class="img_title">Интересное</div>
		<div class="author_name">Молодой казак</div>
	</div>
</div>

<script type="text/javascript" src="{% static 'js/needed.js' %}"></script>
</body>
</html>

home/templates/home/genre_list.html
{% extends "home/base.html" %}

{% block main_content %}{% spaceless %}

{% for genre in genres %}
<a href="{% url 'home:get_genre' genre.slug %}" class="objects_list">{{genre}}</a>
{% endfor %}
{% endspaceless %}{% endblock %}

home/templates/home/header.html
<header class="header">
	<a href="/" class="header_title">LBO</a>
	<nav class="nav">
		<a class="nav_link will_none" href="{% url 'home:home'%}">Главная</a>
		<a class="nav_link" href="{% url 'home:popular' %}">Популярные</a>
		{% if user.is_anonymous %}
		<a class="nav_link" href="{% url 'cabinet:login' %}">Войти</a>
		<a class="nav_link" href="{% url 'cabinet:reg' %}">Регистрация</a>
		{% else %}
		<a class="nav_link" href="{% url 'cabinet:cabinet' user.id %}">Профиль</a>
		<a class="nav_link" href="{% url 'cabinet:logout' %}">Выйти</a>
		{% endif %}
	</nav>
</header>

home/templates/home/home_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>LBO</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/media_queries.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/media/images/icon.png" type="image">
</head>
<body>

{% include "home/header.html" %}

<div class="intro">
	<div class="intro_title">Welcome to LBO</div>
	<a class="read_more" onclick="Read()">Читать</a>
</div>
<div style="width: 100%; height: 15px; background: linear-gradient(black, rgb(208,199,186));"></div>

<div class="main">
	<!--огромный шо пизда код со слайдерами НАЧИНАЕТСЯ-->
	<div class="slider element">
		<a href="{% url 'home:popular' %}" class="genre_title">Популярные</a>
		<div class="description back_inf">Самые популярные произведения от лучших авторов</div>
		<img onclick="back(0)" src="/media/images/back.png" class="right_left" style="left: 10px">

		<div class="slider_wraper">
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="img_title">интересная личность</div>
				<div class="author_name">1</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">2</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">3</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">4</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">5</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">6</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">7</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">8</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">9</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">10</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">11</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">12</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">13</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">14</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">15</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">16</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">17</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">18</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">19</div>
			</div>
			<div class="slide">
				<a href="#">
				<img src="/media/images/book1.jpg" alt="" class="img_slide"></a>
				<div class="author_name">20</div>
			</div>
		</div>

		<img onclick="next(0)" src="/media/images/next.png" class="right_left" style="right: 10px;">
	</div>

	<div class="genre_grid element">
		<a href="{% url 'home:get_genre' 'fantastika' %}" class="genre">Фантастика</a>
		<a href="{% url 'home:get_genre' 'detektiv' %}" class="genre">Детектив</a>
		<a href="{% url 'home:get_genre' 'popadancy' %}" class="genre">Попаданцы</a>
		<a href="{% url 'home:get_genre' 'klassika' %}" class="genre">Класика</a>
		<a href="{% url 'home:get_genre' 'puteshestviya' %}" class="genre">Путешествия</a>
		<a href="{% url 'home:get_genre' 'roman' %}" class="genre">Роман</a>
		<a href="{% url 'home:get_genre' 'rasskaz' %}" class="genre">Рассказ</a>
		<a href="{% url 'home:get_genre' 'boevik' %}" class="genre">Боевик</a>
		<a href="{% url 'home:get_genre' 'fentezi' %}" class="genre">Фэнтези</a>
		<a href="{% url 'home:get_genre' 'litrpg' %}" class="genre">ЛитРПГ</a>
		<a href="{% url 'home:get_genre' 'fanfik' %}" class="genre">Фанфик</a>
		<a href="{% url 'home:get_genre' 'mistika' %}" class="genre">Мистика</a>
		<a href="{% url 'home:get_genre' 'uzhasy' %}" class="genre">Ужасы</a>
		<a href="{% url 'home:get_genre' 'skazka' %}" class="genre">Сказка</a>
		<a href="{% url 'home:get_genre' 'poeziya' %}" class="genre">Поэзия</a>
		<a href="{% url 'home:genre_list' %}" class="genre">Ещё</a>
	</div>	


	<!--ЗАКАНЧИВАЕТСЯ-->
</div>



<script type="text/javascript" src="{% static 'js/needed.js' %}"></script>
<script type="text/javascript">
var allslidecount = 15;
var slidecount = 5;

function Read() {
	a = document.getElementsByClassName("main")[0];
	a.scrollIntoView({ behavior: 'smooth'});
}

</script>
</body>
</html>

home/templates/home/only_text.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{chapter.title}}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/media_queries.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/media/images/icon.png" type="image">
</head>
<body>
{% include "home/header.html" %}


<pre class="text">
	<h1>Глава {{chapter.num}}. {{chapter.title}}</h1>
	{{chapter.txt}}
</pre>

<div class="next_and_right">
{% if back_ %}
<a class="button" href="{% url 'home:chapter' back_.book_id back_.num %}" style="left: 0">Предыдущая</a>
{% endif %}

{% if next_ %}
<a class="button" href="{% url 'home:chapter' next_.book_id next_.num %}" style="right: 0">Следующая</a>
{% endif %}
</div>

<style type="text/css">
	body{
		background: white;
	}
</style>

<script type="text/javascript" src="{% static 'js/needed.js' %}"></script>
</body>
</html>

home/templates/home/section.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/media_queries.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/media/images/icon.png" type="image">
</head>
<body>

{% include "home/header.html" %}

<div class="element section_title">
	<h1>{{title}}</h1>
	<!--
	<select class="select_date">
		<option value="Год">Год</option>
		<option value="Месяц">Месяц</option>
		<option value="День">День</option>
		<option value="Час">Час</option>
	</select>
	-->
</div>

<div class="main_column element">

	<header class="date_header">
		<div onclick="todate(0)" class="date_item">Год</div>
		<div onclick="todate(1)" class="date_item">Месяц</div>
		<div onclick="todate(2)" class="date_item">Неделя</div>
		<div class="date_line"></div>
	</header>

<div class="column_wraper">
		{% for book in books_y %}
{% include "home/book_from_list.html" %}
	{% endfor %}
</div>

<div class="column_wraper">
		{% for book in books_m %}
{% include "home/book_from_list.html" %}
	{% endfor %}
</div>

<div class="column_wraper">
		{% for book in books_w %}
{% include "home/book_from_list.html" %}
	{% endfor %}
</div>
</div>


<div class="second_column will_none">
	<div class="discount element">
		<h1>Скидка на:</h1>
		<img src="/media/images/book3.jpg" alt="" class="img_slide">
		<div class="img_title">Интересное</div>
		<div class="author_name">Молодой казак</div>
	</div>
</div>

<script type="text/javascript" src="{% static 'js/needed.js' %}"></script>
<script type="text/javascript">
	todate(1);
	function todate(n) {
		let a = document.getElementsByClassName("date_line")[0];
		if (n == 0) {
			a.style.left = 0;
			a.style.width = "31.85px"
			column[1].style.display = "none";
			column[2].style.display = "none";
			column[0].style.display = "block"
		}
		if (n == 1) {
			a.style.left = "45.7px";
			a.style.width = "60.3px"
			column[0].style.display = "none";
			column[2].style.display = "none";
			column[1].style.display = "block"
		}
		if (n == 2) {
			a.style.left = (190 - 69.76) + "px";
			a.style.width = "69.76px"
			column[0].style.display = "none";
			column[1].style.display = "none";
			column[2].style.display = "block"
		}
	}

</script>
</body>
</html>

home/templates/home/tag_list.html
{% extends "home/base.html" %}

{% block main_content %}{% spaceless %}

{% for tag in tags %}
<a href="{% url 'home:get_tag' tag.slug %}" class="objects_list">{{tag}}</a>
{% endfor %}
{% endspaceless %}{% endblock %}