LBO/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('cabinet/', include("cabinet.urls")),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cabinet/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'cabinet'

urlpatterns = [
	path('<int:user_id>/', views.cabinet, name='cabinet'),
	path('registration/', views.reg, name='reg'),
	path('login/', views.log, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('add/<int:friend_id>/', views.add_friend, name='add_friend')
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home'

urlpatterns = [
	path('', views.home, name='home'),
	path("popular/", views.popular, name="popular"),
	path("book_create/", views.book_create, name="book_create"),
	path("tag/<str:slug>/", views.get_tag, name="get_tag"),
	path("tags/", views.tag_list, name="tag_list"),
	path("genre/<str:slug>/", views.get_genre, name="get_genre"),
	path("genre/", views.genre_list, name="genre_list"),
	path("book/<int:book_id>/", views.book, name="book"),
	path("book/<int:book_id>/<int:number>/", views.chapter, name="chapter"),
	path('add/<int:book_id>/', views.addbook, name='addbook'),
]

cabinet/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import datetime
from django.utils import timezone

# Create your models here.
class User(AbstractUser):
	about_me = models.CharField(max_length=100, blank=True)
	status = models.CharField(max_length=50, blank=True)
	image = models.ImageField(upload_to="images/", default="images/black.jpg")
	is_on = models.BooleanField(default=True)
	location = models.CharField(default="Neverland", max_length=20)
	birth_date = models.DateField(default=timezone.now)
	#Из-за абстрактой модели пришлось сделать ещё побочную Person

	class Meta:
		verbose_name = 'Пользователь'
		verbose_name_plural = 'Пользователи'


class Post(models.Model):
	text = models.TextField()
	author_name = models.ForeignKey(User, on_delete = models.CASCADE)

	def __str__(self):
		return self.author_name

	class Meta:
		verbose_name = 'Пост'
		verbose_name_plural = 'Посты'

cabinet/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm

class RegForm(UserCreationForm):
	email = forms.EmailField(max_length=254, help_text='')
	username = forms.CharField(max_length = 100, help_text='')
	password1 = forms.CharField(max_length = 100, help_text='')
	password2 = forms.CharField(max_length = 100, help_text='')

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2', ]


class LoginForm(forms.Form):
    username = forms.CharField(max_length=25)
    password = forms.CharField(max_length=100)

cabinet/views.py
from django.shortcuts import render
from .models import User
from .forms import RegForm, LoginForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.utils import timezone
from home.models import Book, Person
from django.db.models.signals import post_save, class_prepared
from django.dispatch import receiver
from requests.exceptions import HTTPError
from django.contrib.auth import logout, authenticate, login

def add_friend(request, friend_id):
	if friend_id == request.user.id:# Ограничение чтобы пользователь не добавлял сам себя в друзья
		return redirect("/")
	to_me = get_object_or_404(User, id=friend_id)
	i_to = get_object_or_404(User, id=request.user.id).person
	print(1)
	i_to.friends.add(to_me)
	print(i_to.friends.all())
	i_to.save()
	return redirect(f'/cabinet/{friend_id}')

def unsubscribe(request, friend_id):
	pass

def reg(request):
	print(dir(request.user))
	message = ''
	form = RegForm(request.POST or None)
	if form.is_valid():
		form.save()
		cd = form.cleaned_data
		user = authenticate(username=cd['username'], password=cd['password1'])
		login(request, user)
		return redirect('/')
	else:
		try:
			errors = form.errors.as_data()
			messages = [i for i in errors]
			message = str(errors[messages[-1]])
			first = message.find("'") + 1
			second = message.rfind("'") - 1
			message = message[first:second]
		except:
			pass
	return render(request, 'cabinet/registration.html', {'user': request.user, 'message': message})

def log(request):
	form = LoginForm(request.POST or None)
	if form.is_valid():
		cd = form.cleaned_data
		user = authenticate(username=cd['username'], password=cd['password'])
		if user is not None:
			login(request, user)
			request.user = 'renat'
			print(request.user, 22)
			return redirect('/')
	return render(request, 'cabinet/login.html', {'user': request.user, })#

def user_logout(request):
	logout(request)
	return redirect('/')
	
def cabinet(request, user_id):
	d = {}
	d['edit'] = False
	if user_id == request.user.id:
		d['edit'] = True
	d['human'] = get_object_or_404(User, id=user_id)
	d['written'] = Book.objects.filter(author_name_id=user_id)
	d['read'] = get_object_or_404(Person, user_id=user_id).read.all
	d["user"] = request.user
	a = d["human"].users.all()
	d['readers'] = a if len(a) < 7 else a[0:6]
	a = d["human"].person.friends.all()
	d['subscriptions'] = a if len(a) < 7 else a[0:6]
	d["in_friends"] = request.user in d["subscriptions"]
	return render(request, "cabinet/cabinet.html", d)


@receiver(post_save, sender = User)
def add_person(instance, **kwargs):
	try:
		person = get_object_or_404(Person, user_id=instance.id) # Если не найдено намерено вызывается ошибка 404
	except:
		person = Person()
		person.user_id = instance.id
		person.save()

cabinet/templates/cabinet/cabinet.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{{human.username}}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/media_queries.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/media/images/icon.png" type="image">
</head>
<body>

{% include 'home/header.html' %}

<div class="container">
	<div class="element for_user_img"><!--Первая страница-->
		<img src="/media/images/silver.png" alt="" class="user_img">
		{% if edit %}
		<a href="#" class="edit back_inf">Редактировать</a>
		{% else %}
		{% if in_friends %}
		<a href="#" class="edit back_inf">Отписаться</a>
		{% else %}
		<a href="{% url 'cabinet:add_friend' human.id %}" class="edit back_inf">Подписаться</a>
		{% endif %}
		{% endif %}
		<div class="back_inf" style="margin: 10px 0 4px 0">Вы являетесь читателем</div>
	</div>
	<div class="fixed_inf element">
	 	<div class="main_inf">
	 		<p class="username">{{human.username}}</p>
	 		<div class="user_status back_inf">{{human.status}}</div>
	 		<div class="manda_inf">
 				<ul class="fixed_inf_row" style="border-top: 1px solid lightgrey; padding-top: 15px;">
 					<li class="th1">День рождения:</li>
 					<li class="th2">{{human.birth_date}}</li>
 				</ul>
 				<ul class="fixed_inf_row">
 					<li class="th1">День регистрации:</li>
 					<li class="th2">{{human.date_joined}}</li>
 				</ul>
 				<ul class="fixed_inf_row" style="border-bottom: 1px solid lightgrey;">
 					<li class="th1">Место проживания:</li>
 					<li class="th2">{{human.location}}</li>
 				</ul>
	 		</div>
	 		<header class="user_nav">
	 			<nav>
		 			<div class="user_section" onclick="user_nav(0)">Профиль</div>
			 		<div class="user_section" onclick="user_nav(1)">Произведения</div>
			 		<div class="user_section" onclick="user_nav(2)">Библеотека</div>
			 		<div class="user_section" onclick="user_nav(3)">Посты</div>
			 	</nav>
		 	</header>
	 	</div>
	</div> 
	{% if human.about_me %}<div class="flex_row about_me element user_full">{{human.about_me}}</div>{% endif %}
	<div class="favorite flex_row element">
		<div class="friend_table">
			<div style="margin-bottom: 20px;">
				<div class="span">
					<h3 class="friends_section" onclick="friends_nav(0)">Читатели</h3>
				</div>
				<div class="span" style="margin-left: 10px;">
					<h3 class="friends_section" onclick="friends_nav(1)">Подписки</h3>
				</div>
			</div>
			<div class="friends">
				{% for friend in readers %} <!-- Читатели-друзья -->
					<a href="{% url 'cabinet:cabinet' friend.user.id %}" class="friend">
						<img src="{{friend.user.image.url}}" alt="" class="friend_img">
						<div class="friend_name">{{friend.user.username}}</div>
					</a>
				{% endfor %}
			</div>
			<div class="friends">
				{% for friend in subscriptions %} <!--Подписки на друзей-->
					<a href="{% url 'cabinet:cabinet' friend.id %}" class="friend">
						<img src="{{friend.image.url}}" alt="" class="friend_img">
						<div class="friend_name">{{friend.username}}</div>
					</a>
				{% endfor %}
			</div>
			<a href="#" style="position: relative; left: 80px; margin-top: 10px; display: block;">Больше</a>
		</div>
		<div><h1 style="text-align: center;">Лучшее по мнению пользователя</h1>
		<div class="slider_wraper">
			<div class="favorite_book">
				<a href=""><img class="img_slide" src="/media/images/silver.png" alt=""></a>
				<div class="back_inf">Имя автора</div>
			</div>
			<div class="favorite_book">
				<a href=""><img class="img_slide" src="/media/images/silver.png" alt=""></a>
				<div class="back_inf">Имя автора</div>
			</div>
			<div class="favorite_book">
				<a href=""><img class="img_slide" src="/media/images/silver.png" alt=""></a>
				<div class="back_inf">Имя автора</div>
			</div>
			<div class="favorite_book">
				<a href=""><img class="img_slide" src="/media/images/silver.png" alt=""></a>
				<div class="back_inf">Имя автора</div>
			</div>
			<div class="favorite_book">
				<a href=""><img class="img_slide" src="/media/images/silver.png" alt=""></a>
				<div class="back_inf">Имя автора</div>
			</div>
		</div></div>
	</div>
	{% if written %}<div class="library flex_row element"><!--Написанные книги-->
		<h1>Написанные книги</h1>
		{% for book in written %}
			<div class="favorite_book book_m">
				<a href="{% url 'home:book' book.id %}"><img class="img_slide" src="{{book.image.url}}" alt=""></a>
				<div class="back_inf">{{book.author_name}}</div>
			</div>
		{% endfor %}
	</div>{% endif %}
	{% if read %}<div class="library flex_row element"><!--Библеотека-->
		<h1>Библеотека</h1>
		{% for book in read %}
			<div class="favorite_book book_m">
				<a href="{% url 'home:book' book.id %}"><img class="img_slide" src="{{book.image.url}}" alt=""></a>
				<div class="back_inf">{{book.author_name}}</div>
			</div>
		{% endfor %}
	</div>{% endif %}
	{% if read %}<div class="library flex_row element"><!--Посты-->
		<h1>Посты</h1>
		{% for book in read %}
			<div class="favorite_book book_m">
				<a href="{% url 'home:book' book.id %}"><img class="img_slide" src="{{book.image.url}}" alt=""></a>
				<div class="back_inf">{{book.author_name}}</div>
			</div>
		{% endfor %}
	</div>{% endif %}
</div>

{% include 'home/footer.html' %}

<script type="text/javascript" src="{% static 'js/needed.js' %}"></script>
<script type="text/javascript">
window.onload = function() {
	friends_nav(0);	
	user_nav(0);
}

function user_nav(n) {//навигация по Библеотека Произведения ...
	let a = document.getElementsByClassName('user_section');
	let m = document.getElementsByClassName('flex_row');
	let d = ['flex', 'inline-block', 'inline-block', 'inline-block']
	for (var i = 0; i <= 3; i++) {
		a[i].style.color = 'darkgrey';
	}
	a[n].style.color = 'black';
	if (n == 0) {
		for (var i = 0; i < 3; i++) {
			m[i].style.display = d[i];
		}
		m[3].style.display = 'none';
	}
	else{
		for (var i = 0; i <= 3; i++) {
			m[i].style.display = 'none';
		}
	}
	m[n].style.display = d[n]
	document.getElementsByClassName('about_me')[0].style.display = 'none';
}

function friends_nav(n) {
	let section = document.getElementsByClassName('friends_section');
	let  friends = document.getElementsByClassName('friends');
	let index = 1 - n;
	friends[index].style.display = 'none';
	friends[n].style.display = 'block';
	section[index].style.color = 'grey';
	section[n].style.color = 'black';
}

</script>
</body>
</html>

cabinet/templates/cabinet/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Авторизоваться</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/media_queries.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/media/images/icon.png" type="image">
</head>
<body>

{% include 'home/header.html' %}


<form method="post" class="reg_body" style="padding-top: 150px">
{% csrf_token %}
<p style="color: white; font-size: 40px; text-align: center; margin-bottom: 0;">Авторизоваться</p>
<input type="text" name="username" maxlength="100" autofocus required id="id_username" class="field" placeholder="Username...">
<input type="password" name="password" maxlength="100" required id="id_password1" class="field" placeholder="Password...">
<input type="submit" value="Авторизоваться" class="send_button">
{% if message %} <div class="field" style="margin-top: 10px; color: lightgrey; font-size: 21px;">{{message}}</div> {% endif %}
</form>

<script type="text/javascript" src="{% static 'js/needed.js' %}"></script>
</body>
</html>

cabinet/templates/cabinet/registration.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Регистрация</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/media_queries.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" href="/media/images/icon.png" type="image">
</head>
<body>

{% include 'home/header.html' %}


<form method="post" class="reg_body">
{% csrf_token %}
<p style="color: white; font-size: 40px; text-align: center; margin-bottom: 0;">Регистрация</p>
<input type="text" name="username" maxlength="100" autofocus required id="id_username" class="field" placeholder="Username...">
<input type="email" name="email" maxlength="254" required id="id_email" class="field" placeholder="Email...">
<input type="password" name="password1" maxlength="100" required id="id_password1" class="field" placeholder="Password...">
<input type="password" name="password2" maxlength="100" required id="id_password2" class="field" placeholder="Again...">
<input type="submit" value="Зарегестрироваться" class="send_button">
{% if message %} <div class="field" style="margin-top: 10px; color: lightgrey; font-size: 21px;">{{message}}</div> {% endif %}
</form>

<script type="text/javascript" src="{% static 'js/needed.js' %}"></script>
</body>
</html>